### ISSUE TITLE
Better Bluetooth Resetting 

### ISSUE THREAD

**Issue by MarvinNazari** [Polidea/RxBluetoothKit#144]
So CoreBluetooth sometimes throws bluetooth resetting which is basically `BTServer` crashing inside `iOS` right now RxBluetoothKit throws the `bluetoothResetting`.

You will get `CoreBluetooth[ERROR] XPC connection interrupted, resetting.` in console.

If I'm not wrong the easiest way to handle this correctly is that you need to remove all the peripheral, services, characteristics that `BluetoothManager` have stored and reinit `CBCentralManager` and basically start all over.

Im not saying that RxBluetoothKit should handle this, but a function in `BluetoothManager` which u are enable to reset the stuff above will be really helpful, I'm interested to know how u guys handle this issue as well.

BlueCap does something similar [here](https://github.com/troystribling/BlueCap/blob/master/BlueCapKit/Central/CentralManager.swift#L101-L113)

**Comment by Kacper20** [comment]
Will think about it. Problem is that our `CBCentralManager` instance is injected from the outside. This makes things complicated and would definitely require breaking the API (because instead object we should take a closure that returns object and use it at start and every time when bluetooth is reseting).

**Comment by Kacper20** [comment]
We think that you should just re-initialize the `BluetoothManager` if anything like that happens. Because we're injecting `CBCentralManager` we don't see a way to implement this in a clear way. 
Doing more operations is outside of the library scope. Also it has it's benefits — we're ensuring that all of the state internal object is cleared just because it's deallocated. It makes us certain that we don't need to remember about clearing whenever we're adding any internal storage to the `BluetoothManager`.

If you have some further thoughts — feel free to re-open the issue. I'm open to the discussion about this feature.
