### ISSUE TITLE
Add disconnect from peripheral method

### ISSUE THREAD

**Issue by larryonoff** [Polidea/RxBluetoothKit#278]
`disconnect` method was removed from version 5.0. So developers only can disconnect from peripheral by disposing disposable of `establishConnection` method.

As result developers cannot `disconnect` when connection to peripheral restored via state restoration.

Any thoughts about it?

**Comment by paweljaneczek** [comment]
Hey @larryonoff.
In order to disconnect from `Peripheral` that was retrieved via restored state you just need to take `Peripheral` from `CentralManagerRestoredState.peripherals` and do
```swift
let connectedDisposable = peripheral.establishConnection().subscribe(...)
connectedDisposable.dispose()
```

Simply `RxBluettothKit` allows to `establishConnection` for peripherals that were not connected within instance of `CentralManager` (under the hood it checks if device is connected from outside library, and if it is connected that it is returning disconnect observable, so you can disconnect from device via `dispose`)

**Comment by larryonoff** [comment]
@pawelByszewski huh. Thank you very much!

I think this should be added into documentations / samples somewhere.

**Comment by paweljaneczek** [comment]
I agree, will add this soon. Thanks!

**Comment by larryonoff** [comment]
@paweljaneczek  One more question in this thread. How to avoid `.peripheralIsAlreadyObservingConnection` error?

**Comment by paweljaneczek** [comment]
If you get `.peripheralIsAlreadyObservingConnection` it means that you already have ongoing `establishConnection` observable for that `Peripheral`. 
As I understand you are trying to connect to device that was already connected from different place in code. You should avoid that situations because that can lead to numerous of bugs in your application. 
Best practice is to create some facade or wrapper for you BLE communications and store there disposables for connected peripherals.

**Comment by larryonoff** [comment]
Thank you for the feedback. I've already created wrapper for storing connections. I have some ideas how to avoid this error.
