### ISSUE TITLE
How to reconnect when connection is lost with peripheral

### ISSUE THREAD

**Issue by avdwerff** [Polidea/RxBluetoothKit#281]
I'm trying to establish reconnection when connection is last (because of peripheral is out of range, or turned of for a while). In RxBluetooth there is the observe for disconnection, I use that to try to connect again on this event, but I get an error stating that you can't do operations on a disconnected device. I wonder what the best approach would be for this use case with RxBluetoothKit. Should I scan with retry and timeout operators?

**Comment by bartoszstelmaszuk** [comment]
If a disconnection is caused by out of range or turned off device you should scan before connecting to it again. If not you will end up connecting to a disconnected device as you said.

Scan looks like reasonable option to solve it. Not sure if there are needs to make retries or any timeouts. Scan should return device when it will be again scannable.

If this answer doesn't hep try to write down the problem in more detail on our [gitter channel](https://gitter.im/RxBLELibraries/RxBluetoothKit?utm_source=share-link&utm_medium=link&utm_campaign=share-link) or write a question on [StackOverflow](https://stackoverflow.com/questions/tagged/rxiosble?sort=active)
