### ISSUE TITLE
Thoughts on adding CBPeripheralManager to the kit?

### ISSUE THREAD

**Issue by AndrewSB** [Polidea/RxBluetoothKit#29]
I was going to tackle this in a PR - any suggestions/ insight before I start?

**Comment by AndrewSB** [comment]
Would it make sense to move all the CentralManager code into a sub-object? Something like Bluetooth.CentralManager & Bluetooth.PeripheralManager?

**Comment by Kacper20** [comment]
That's great!
My only suggestion is to try to follow our conventions to delegates to be consistent across the whole library.
About naming - I would advise to first try to implement it separately, as a non breaking addition to the lib - maybe some object called `BluetoothPeripheralManager`. Later we could think about naming. We don't want to make big changes here(to the existing codebase), so that users of the lib would not have to worry about big breaking changes. 
I'm really looking forward to your contribution. If you have any questions - feel free to let us know and we'll be happy to discuss them.

**Comment by AndrewSB** [comment]
will do! Thanks @Kacper20.

Created #30 to track my progress & for discussion
