### ISSUE TITLE
You cannot call establishConnection when the connection is already established

### ISSUE THREAD

**Issue by vladiulianbogdan** [Polidea/RxBluetoothKit#295]
Right now, if `establishConnection` is called after the connection is already established, the subscription will error with the following message: "You cannot try to establishConnection to peripheral when you have ongoing connection".

Here is a simplified example that illustrates an use case where I am having problems with the current API:

```
let discoverConnectedDevices = bluetoothManager.retrieveConnectedPeripherals(withServices: [])
            .flatMap { peripheral -> Observable<Peripheral> in
                return peripheral.establishConnection()
            }
            .flatMap { peripheral -> Observable<[Service]> in
                return peripheral.discoverServices(nil)
            }
            // Some more logic based on characteristics and services that helps me discover the device that I want
            .map { peripheral in
                peripheral.identifier
            }
            
        someInput
            .flatMapLatest {
                discoverConnectedDevices
            }
            .flatMap { uuid -> Single<Void> in
                let peripheral = bluetoothManager.retrievePeripherals(withIdentifiers: [uuid]).first!
                
                peripheral.establishConnection()
            }
            .subscribe()
```

We have an observable that discovers the connected devices and calls `establishConnection` in order to figure out if this is the device that we need (we have to get some info from a characteristic). Because of legacy code reasons, when the device is successfully discovered, I have to pass the peripheral identifier and retrieve the peripheral again and re-establish the connection. The problem is that the second `establishConnection` is called before the subscription to `discoverConnectedDevices` is disposed.

I am thinking that one way to work around this is to make `establishConnection` a shared observable that keeps the connection alive as long as there is at least one subscription instead of sending an error when a second observer comes in.

I would like to hear from you what was the reasoning behind the current implementation.

**Comment by bartoszstelmaszuk** [comment]
Thank you for using the library.

What you suggest was previous implementation to make connection a shared observable. We gave up on this solution since often users put traps on themself creating multiple connections to the same peripheral without proper management over them. Still you can make multiple connection observables but you must shared it explicit in your code. It makes us know that you have 100% awareness of what you are doing :)

How to do it in you case is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/search?q=rxiosble) with **rxiosble** tag. Also feel free to check already posted questions as a similar one may be already answered.
