### ISSUE TITLE
Example code running iOS13 - Thread 2: signal SIGABRT Error

### ISSUE THREAD

**Issue by hohaidang** [Polidea/RxBluetoothKit#357]
iOS 13.2.2
<img width="1536" alt="Screen Shot 2019-11-16 at 11 48 33" src="https://user-images.githubusercontent.com/22592185/68987654-bd164700-086e-11ea-839a-cb69dd012f1e.png">

**Comment by robbaltzer** [comment]
Seems like this error started happening when I upgraded my apple devices to iOS 13.3.1. iOS releases before that seem to be OK.

**Comment by robbaltzer** [comment]
Alamofire and other frameworks are having the same issue: https://github.com/Alamofire/Alamofire/issues/3051

Looks like it will be fixed in 13.4. Until then, this fixed it for me:

"
I had same issue with Alamofire, and solved it by removing use_frameworks! from pod file  then in console pod deintegrate, pod update and pod install
Now everything works fine.
"
