### ISSUE TITLE
warnning:

### ISSUE THREAD

**Issue by swieer** [Polidea/RxBluetoothKit#71]
[CoreBluetooth] API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported

**Comment by Kacper20** [comment]
Could you provide a snippet of code to clarify things?

**Comment by swieer** [comment]
@Kacper20 ,use Swift3.0, iOS10.0.2, Example project. running on iPhone5s.
Sorry, My English is poor
Thanks!

**Comment by Kacper20** [comment]
Hi there,
We think that there's nothing to be worried about. We have delegate which implements all of the `CBCentralManagerDelegate` methods. Since you're not using state restoration, and we implement all of the methods - this warning occurs. 
We will think about a way to get rid of this warning, but this is nothing you should be worried about.

Does this answers your concerns?
Thanks for feedback :)

**Comment by z4gunn** [comment]
If you plan in using BLE state restoration then you have to check "Uses Bluetooth LE accessory" in the "Background Modes" section of the Capabilities tab, which will silence this error.  Also this warning becomes an error in Swift 3.2 / Xcode 8.3.

![image](https://cloud.githubusercontent.com/assets/19891556/25307324/017494d2-2754-11e7-8c1b-64c20920651a.png)
